### PR TITLE
Add jetton onchain metadata support

### PR DESCRIPTION
**Pull request by shaharyakir**
See #189 

This adds support for reading metadata for jettons which is stored onchain, alongside the existing offchain support.

image

Example jetton address: EQDfLSpVoAYo9_reMujMv6QFGDI4vntaVgzGGrAImwL3zeZC

Tested on Android/RN.

### CODE REVIEW

**Comment by ex3ndr** [comment]
Hello! We are still reviewing and not forgetting about this PR the problem is that we will move to backend-based metadata or hardcode all good coins, and we are still figuring out the best way to do so.

**Comment by shaharyakir** [comment]
Anything we can do to help decide and/or contribute to implementing the backend code for onchain parsing?

Re hardcoding good coins, as a user I probably would still like to see all of my jettons, maybe some would be hidden under a folder if not verified or marked as verified if they belong in the list?

**Comment by shaharyakir** [comment]
Giving it more thought, parsing jetton metadata in the backend may well be defeating the purpose of storing these metadata on chain. The less processing is done on a proprietary backend, the safer it is for the user.

**Comment by ex3ndr** [comment]
Hello! Our current implementation relies on our backend for now and supports on-chain metadata. Eventually, we will be able to move everything on-chain to a specific contract that is managed by some DAO and we will remove dependency from our backend.

**Comment by shaharyakir** [comment]
@ex3ndr thanks for the update, I tested it with previously created jettons and a new one, currently they are not displayed in tonwhales explorer nor the wallet.

Was it supposed to work already?

(Example jetton - https://jetton.live/jetton/EQD8a5p-Imf9cU55wB66guXwNSGv8lSGg-zFregbVXY0V51L)

**Pull request closed without merging**
